### ISSUE TITLE
Hello, I can’t connect to MySQL server, I have error

### ISSUE THREAD

**Issue by DifficultPhil** [AuthMe/AuthMeReloaded#2404] opened 2021-08-20 03:55 UTC
Ubuntu 20.04, mysql 8, utf8mb4, authme 5.6 beta
Error: Unknown character set index for field '255' received from server.

Help me please

**Comment by sgdc3** [comment] 2021-08-21 20:21
Duplicate of #1779

**Closed by sgdc3** 2021-08-21 20:21 UTC
Labels: Type: bug
