### ISSUE TITLE
Sending the player to the last server he was on

### ISSUE THREAD

**Issue by ham1255** [AuthMe/AuthMeReloaded#1852] opened 2019-07-05 22:35 UTC
as title said how to do it becuase when auth finshs it teleport the player to another server

**Comment by ham1255** [comment] 2019-07-05 22:44
forgot to says its bungeecord

**Comment by ljacqu** [comment] 2019-07-06 12:50
Possibly duplicate of #1833

**Comment by ham1255** [comment] 2019-07-06 12:54
here Player is on skywars server and he quit then rejoins back login but he being sent the lobby not server he was on

**Closed** 2020-12-27 05:28 UTC
Labels: Topic: bungeecord
