### ISSUE TITLE
Add hashing support for Argon2

### ISSUE THREAD

**Issue by mat41997** [AuthMe/AuthMeReloaded#1150] opened 2017-03-27 17:45 UTC
https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/hash_algorithms.md

argon2
https://github.com/p-h-c/phc-winner-argon2

scrypt
https://github.com/Tarsnap/scrypt

other
https://github.com/lenis0012/LoginSecurity-2/tree/master/src/main/java/com/lenis0012/bukkit/loginsecurity/hashing/active

table

![table](https://cloud.githubusercontent.com/assets/5884000/24369889/c2263606-1325-11e7-9937-ada14684a543.png)

**Comment by ljacqu** [comment] 2017-03-27 19:23
we can do it with https://github.com/wg/scrypt, which is even on Maven central

**Comment by Eyremba** [comment] 2017-03-30 16:04
This is useless. I already posted this some time ago:

> Maybe take a look at Argon2? Argon2 is currently the most secure password hashing algorithm, even more secure than scrypt. It could be a milestone too for 5.4.

> Original Argon2 source: https://github.com/P-H-C/phc-winner-argon2
Java implementation of Argon2: https://github.com/phxql/argon2-jvm

Argon2 is much more secure than Scrypt and much better. Implementing scrypt would just implement an old outdated algorithm...

**Comment by timvisee** [comment] 2017-03-30 16:54
Maybe, implementing some dynamic hashing solution might be the best idea. With that, I mean a solution that supports many known hashing algorithms without requiring changes in the code regarding hashing, with minimal code change (for the initial implementation). Except for a little configuration change however. It would be awesome if the server administrator would have the ability to configure what algorithm is used using some form of algorithm identifier string, whether that'd be a `bcrypt`, `scrypt`, `Argon2` or `/dev/random`.

The problem is, that a single algorithm isn't ideal for all situations. Generally speaking, a hashing algorithm that takes longer (in time) to hash, is more secure against brute force attacks. However, that also means that the longer it takes to hash, the more resource expensive it is. And that for each hash calculation that needs to be done when a user enters a password through the login command. Some hashing algorithms even occupy all available CPU cores, which can cause great performance issues on servers running lots of users, or on low performance servers. I've heard that Facebook even uses dedicated hashing servers to minimize the performance impact for users that are logging in on their regular servers, although I don't know whether that is true.

Giving the server administrator freedom to choose an appropriate hashing algorithm would be ideal in my honest opinion. Purely implementing something like this might be a bit overkill solely for the reason mentioned above. But, some users seem to like different hashing implementations, thus something like this would be a perfect solution. Many other bigger projects that are focused on password security implement some form of this. And of course, it provides many pro's.

I've seen something like this a few weeks ago, with many supported hashing algorithm adapters, although I can't remember what it was called right now. Maybe it has been mentioned before.

What does everybody think about this?

**Comment by ljacqu** [comment] 2017-03-31 05:55
@timvisee Your efforts are very welcome (and we have tons of stuff that needs work!) but I think they'd be better spent on another subject.

It's generally a bad idea to mix hashing algorithms. The only legitimate reason for doing this is to hook into an existing system like a forum. There, admittedly, it needs the introduction of a new hash algorithm for it to work. 

Given that we sometimes use the configured hash algorithm as an indiciation to perform forum-specific stuff (e.g. XFBCRYPT I think is just bcrypt but it triggers additional work in the data source) I fear that we won't be able to simplify the settings that way.

Bcrypt does a good job of hashing in many iterations. One improvement we can do there is in the settings. I don't think they're clear at all (on mobile, but I think one is called bcryptRoundsLog2 or similar and the comment just restates that xD)

**Comment by ljacqu** [comment] 2017-03-31 06:03
What could be interesting is hashing some algorithm multiple times: `hash1(hash2(hash3(...hashn(pass + salt) + pass + salt) + pass + salt)...) + pass + salt)` where `n` and maybe `hash` are configurable. But that's essentially Bcrypt, I'd still vouch for making Bcrypt more accessible

**Comment by Eyremba** [comment] 2017-03-31 14:34
> . But that's essentially Bcrypt, I'd still vouch for making Bcrypt more accessible

Bcrypt is OLD and INSECURE when you attack it with modern methods. Like stated multiple times, Bcrypt has been replaced by Scrypt, and Scrypt has been replaced by Argon2. Argon2 is the newest and currently most secure method.

**Comment by timvisee** [comment] 2017-03-31 14:47
@Eyremba Is it? Is there any proof for that statement?

Is it because it doesn't require much performance to brute force? The cool think about bcrypt is, that you can configure how much iterations to use while hashing. This increases the hashing time exponentially. Also, brypt uses a random salt for each hash further strengthening the security.

**Comment by Eyremba** [comment] 2017-03-31 14:52
> @Eyremba Is it? Is there any proof for that statement?

Wtf just google it! Argon2 is the official successor of Bcrypt and Scrypt.

> The cool think about bcrypt is, that you can configure how much iterations to use while hashing.

And...? Argon2 can do even more. You can specify the iterations, and also the memory consumption and other things to prevent other attacks.

Also, Argon2 has won the official PHC!

-->

> Argon2 is a key derivation function that was selected as the winner of the Password Hashing Competition in July 2015.

--> https://en.wikipedia.org/wiki/Argon2

It has also won against Bcrypt and Scrypt....

--> https://github.com/p-h-c/phc-winner-argon2

**Comment by Gnat008** [comment] 2017-03-31 15:01
https://security.stackexchange.com/questions/4781/do-any-security-experts-recommend-bcrypt-for-password-storage/6415#6415

As a note with security algorithms, older does not inherently mean worse or less secure. Nor does something newer mean more secure. Older ones have been tested by time in the wild. 

As another note, NIST recommends PKDBF (prolly misspelled, on mobile) for a security hashing algorithm.

**Comment by Eyremba** [comment] 2017-03-31 15:11
> As another note, NIST recommends PKDBF (prolly misspelled, on mobile) for a security hashing algorithm.

That's because they have not tested Argon2 yet, however, Argon2 has won the official Password Hashing Competition in July 2015.

And just as another note, the popular password manager "KeePass" which is used by millions of people uses Argon2 too since the last version/release.

**Comment by Gnat008** [comment] 2017-03-31 15:27
Congratulations. Doesn't mean I'm gonna necessarily trust the latest and greatest, for exactly the reasons I gave above. 

Maybe it is better. But maybe it has a critical flaw that we don't know about yet because it hasn't spent too long in the wild. 

See what I'm getting at here?

**Comment by sgdc3** [comment] 2017-04-14 16:05
We implemented Argon2 ;)

**Comment by sgdc3** [comment] 2017-06-01 10:44
Due to devbukkit limitations we can't publish a jar containing binaries (argon2 implementation has some dlls)

**Comment by Eyremba** [comment] 2017-06-01 15:48
> Due to devbukkit limitations we can't publish a jar containing binaries (argon2 implementation has some dlls)

Could you please make it so that if a user wants to use Argon2, he can download the Argon2 Library here on GitHub manually and put it into the AuthMe config folder?

**Comment by Xephi** [comment] 2017-06-01 17:15
We can maybe add a profile to generate it but do not publish on bukkit ^^"

**Comment by sgdc3** [comment] 2017-06-01 17:50
critical? xD

**Comment by mat41997** [comment] 2017-06-01 18:02
yes, this function is very important

**Comment by sgdc3** [comment] 2017-06-01 18:30
Not critical

**Comment by Xephi** [comment] 2017-06-01 18:34
When you got regression in code, put it at critical :O

**Comment by sgdc3** [comment] 2017-06-01 19:08
We have more important stuff to do, and we are all very busy atm. So much to do and no time. :/

**Comment by ljacqu** [comment] 2017-06-01 19:31
I'm conflicted because I agree with both of you :P

**Comment by Xephi** [comment] 2017-06-01 19:32
I'm working on it actually to bring it live

**Comment by Xephi** [comment] 2017-06-01 23:01
Working branch here :
https://github.com/AuthMe/AuthMeReloaded/tree/topic/argon2

To compile/use this version, you have to install the argon2 library : 

``` bash
git clone https://www.github.com/P-H-C/phc-winner-argon2.git argon2-src ;
cd argon2-src && sudo make && sudo make install;
```

**Comment by Xephi** [comment] 2017-06-01 23:02
Will be merged when i found a way to ignore test suite for Argon2 if the library doesn"t exist on the system
Can actually be build via jenkins (already test it)
@ljacq  @sgdc3 i let you finalize the process :3

**Comment by sgdc3** [comment] 2017-06-02 01:06
just keep the test disabled, we enable it with a specific maven profile like we did with skipLongHashTest

**Comment by ljacqu** [comment] 2017-06-02 03:34
Hi @Xephi
My username is ljacq**u** btw
Could we have a Wiki page explaining how to install Argon2 for Authme? This is the first question we will get ;)
Also should we fall back to SHA256 if Argon2 is configured but unavailable? I expect that now in this case, AuthMe becomes unusable even for new registrations. Not sure what the best thing is to do here

**Comment by Xephi** [comment] 2017-06-02 08:06
Sorry :3 
Yeah, i'll write something in the wiki to explain how to :/ 
A fall back is a bad idea, since if a server admin use argon2, he must know what he's doing. Btw, we just check if the native library is present in the library path, you can simply install it on the system, or add it in the spigot lib folder

**Comment by krusic22** [comment] 2017-07-19 21:14
What paths get checked for the lib? I tried installing it using apt and npm non get detected... 
(I'm using Debian btw)

**Comment by sgdc3** [comment] 2017-07-20 01:03
@xephi

**Comment by games647** [comment] 2017-07-20 08:09
>What paths get checked for the lib? 

For a 64bit machine
* /usr/java/packages/lib/amd64
* /usr/lib64
* /lib64
* /lib
* /usr/lib

>I tried installing it using apt and npm non get detected...
(I'm using Debian btw)

It appears to be that debian ships only the argon2 executable, but java needs the library file (.so). Only Arch and Suse provides this library in their repositories. 

But as @Xephi described you could easily compile it yourself.

https://github.com/AuthMe/AuthMeReloaded/issues/1150#issuecomment-305644034

**Comment by krusic22** [comment] 2017-07-20 10:21
I have libargon2.so in /usr/lib but it doesn't get detected. Tried compiling it just like @Xephi said but it still doesn't get detected.

**Comment by games647** [comment] 2017-07-20 10:43
How do you installed it with `sudo make install` ?

**Comment by krusic22** [comment] 2017-07-20 10:44
Yes.

**Comment by Xephi** [comment] 2017-07-20 10:45
You can install it by downloading source code, make and make install it :)

Le 20 juil. 2017 12:44, "Kristjan Krušič" <notifications@github.com> a
écrit :

Yes.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AuthMe/AuthMeReloaded/issues/1150#issuecomment-316666655>,
or mute the thread

**Comment by sgdc3** [comment] 2017-07-20 10:47
@Xephi Pls finish the wiki XD

**Comment by sgdc3** [comment] 2017-07-20 10:47
so we can close this issue

**Comment by games647** [comment] 2017-07-20 10:54
@krusic22 Could you run `file /usr/lib/libargon2.so` maybe it's broken?

**Comment by krusic22** [comment] 2017-07-20 11:01
I get "/usr/lib/libargon2.so: symbolic link to libargon2.so.0"
/usr/lib/libargon2.so.0: ELF 64-bit LIB shared object,.....

**Comment by games647** [comment] 2017-07-25 13:37
@krusic22 You use the topic/argon2 branch? What exact error do you get in Spigot?

**Comment by krusic22** [comment] 2017-07-25 13:55
Yes. It doesn't give a error just reverts to SHA256. OracleJDK.

**Comment by games647** [comment] 2017-07-25 13:56
What config value do you put in there?

**Comment by krusic22** [comment] 2017-07-25 14:04
ARGON2 also tried just ARGON.

**Comment by games647** [comment] 2017-07-25 14:14
For me it crashes if I put ARGON2 in there and don't have the library installed:
>[WARN]: [AuthMe] Cannot find libargon2 [UnsatisfiedLinkError]: no argon2 in java.library.path
[WARN]: [AuthMe] WARNING!!! You use Argon2 Hash Algorithm method but we can't found any Argon2 library on your system !
[WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!!

If the library is installed, it works fine.

**Comment by mat41997** [comment] 2017-07-25 14:22
@games647 How to run Argon2 in windows 10?

**Comment by games647** [comment] 2017-07-25 14:40
@mat41997 
Download a compiled library for your architecture from [here](https://github.com/phxql/argon2-jvm/tree/master/src/main/resources) or compile it yourself. Then install the dll to one folder specified in your PATH variable. You could execute `set path` to view all possible locations separated by a semicolon. You could also use `-Djava.library.path=<absolute path>` as your Java startup parameter.

**Comment by sgdc3** [comment] 2017-09-14 23:03
@Xephi any news about that? ;)

**Comment by Xephi** [comment] 2017-09-15 08:42
It actually works, i've to write the wiki page T.T

**Comment by Eyremba** [comment] 2017-09-17 18:07
Just by the way, this here: https://github.com/andreas1327250/argon2-java is a pure Java implementation of Argon2.

It could be maybe implemented into AuthMe, and it would not require any external libraries or dlls or stuff.

**Comment by ljacqu** [comment] 2017-09-17 18:24
That's pretty cool, I would immediately favor that over anything that requires additional steps. Looks like it still needs a little to be mature, though. Maybe I could help out a little.

**Comment by Eyremba** [comment] 2017-09-17 20:04
> Looks like it still needs a little to be mature, though.

Yes. The last changes in the repo were made 5 days ago, so yes it is currently in active developement.

But maybe it could be used in AuthMe soon. I have tested this Argon2 version, and it seems to be pretty stable. Also, AuthMe could pull the latest version of Argon2 everytime before a AuthMe release is compiled.

**Comment by Xephi** [comment] 2017-10-22 22:11
Available on master branch

**Comment by ljacqu** [comment] 2017-10-23 16:13
Hi @Eyremba @mat41997, we'd be thankful for some feedback :)

**Comment by ljacqu** [comment] 2017-10-23 16:15
Confirmed by krusic22 on Discord that it works, so I close again xP Sorry

**Closed by ljacqu** 2017-10-23 16:15 UTC
Labels: Status: please verify, Type: enhancement

**Comment by mat41997** [comment] 2017-10-23 16:31
i have one error
```
[18:29:49] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.4-SNAPSHOT-b1842
[18:29:49] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[18:29:49] [Server thread/INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[18:29:49] [Server thread/INFO]: [AuthMe] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[18:29:49] [Server thread/WARN]: [AuthMe] Cannot find argon2 library: https://github.com/AuthMe/AuthMeReloaded/wiki/Argon2-as-Password-Hash [UnsatisfiedLinkError]: no argon2 in java.library.path
[18:29:49] [Server thread/WARN]: [AuthMe] WARNING!!! You use Argon2 Hash Algorithm method but we can't find the Argon2 library on your system! See https://github.com/AuthMe/AuthMeReloaded/wiki/Argon2-as-Password-Hash
[18:29:49] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[18:29:49] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[18:29:49] [Server thread/INFO]: [AuthMe] AuthMe 5.4-SNAPSHOT-b1842 disabled!
[18:29:49] [Server thread/INFO]: [AuthMe] Development builds are available on our jenkins, thanks to f14stelt.
[18:29:49] [Server thread/ERROR]: Error occurred while enabling AuthMe v5.4-SNAPSHOT-b1842 (Is it up to date?)
java.lang.NullPointerException: null
	at fr.xephi.authme.ConsoleLogger.writeLog(ConsoleLogger.java:240) ~[?:?]
	at fr.xephi.authme.ConsoleLogger.info(ConsoleLogger.java:115) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:155) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1244]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[18:29:49] [Server thread/INFO]: Done (1,977s)! For help, type "help" or "?"
[18:29:49] [Server thread/INFO]: Stopping server
```

**Comment by lenis0012** [comment] 2017-11-26 03:16
Intresting conversation.

I implemented Argon2 a while ago, but never documented it because I was unable to find enough evidence proving that the algorithm is "battle tested".

I also considered a custom hashing method where multiple algorithms could be combined. but for the same reasons decided not to implement it.

I am getting Déjà vu scrolling through this page.

On another note, nice work guys.
AuthMe Reloaded appears to have improved a lot in the past 2 years or so.

**Comment by sgdc3** [comment] 2017-11-26 10:31
@lenis0012 Thank you man ;)

**Comment by Graxo** [comment] 2024-08-22 18:16
> For me it crashes if I put ARGON2 in there and don't have the library installed:
> 
> > [WARN]: [AuthMe] Cannot find libargon2 [UnsatisfiedLinkError]: no argon2 in java.library.path
> > [WARN]: [AuthMe] WARNING!!! You use Argon2 Hash Algorithm method but we can't found any Argon2 library on your system !
> > [WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!!
> 
> If the library is installed, it works fine.

How do i install the library?
