### ISSUE TITLE
Error in console of hub server when i wand /authme purge

### ISSUE THREAD

**Issue by DiktatorAladeen** [AuthMe/AuthMeReloaded#2663] opened 2023-01-03 23:48 UTC
### What behaviour is observed?

Hii,

 I am trying to purge players data but this error is happening in console on my hub server. I have bungee and 4 servers are connected with this authme.

### Expected behaviour

I thought they would delete all data from players older than 100 days because there are too many accounts.

### To Reproduce

When i try /authme purge 100

### Plugin list

![image](https://user-images.githubusercontent.com/34982264/210459731-3a27ff46-79be-41c1-9f8d-64ad97c13f09.png)

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

https://prnt.sc/3KQBdhAwtDt4

### Error log (if applicable)

https://pastebin.com/jZ62h0ub

### Configuration

https://pastebin.com/HGpvsvKJ

**Comment by ljacqu** [comment] 2023-01-04 21:25
Duplicate of  #2488, which I‘ll try to look at in the next two weeks (I have quite a few things going on this week)

**Closed by ljacqu** 2023-01-04 21:25 UTC
Labels: Type: bug
