### ISSUE TITLE
Field realname not working properly when using external registration method

### ISSUE THREAD

**Issue by hsombini** [AuthMe/AuthMeReloaded#1319] opened 2017-08-22 15:25 UTC
### What behaviour is observed:
When using external registration, the field "realname" is not considered until a restart or a reload is performed on AuthMe.

### Steps/models to reproduce:
1. Startup the server

2. Register using this query:
insert into authme (username, realname, password, , email) values ('test', 'Test', '123123')

3. Try to login as Test

4. You'll not be able to login, AuthMe wil require you to login with "test" instead

5. Reload AuthMe or restart the server

6. Try to login as "test"

7. AuthMe will require you to login as "Test" since it's finally using the data from "realname" field

### AuthMe build number:
1758

**Comment by sgdc3** [comment] 2017-09-30 17:09
@hsombini Still happening? The code looks fine.

**Comment by sgdc3** [comment] 2017-10-09 08:01
You have to disable caching i think.

**Comment by ljacqu** [comment] 2017-10-29 17:41
Closing as I cannot reproduce this bug with `preventOtherCase: true`

**Closed by ljacqu** 2017-10-29 17:41 UTC
Labels: Status: awaiting answer, Type: bug
