### ISSUE TITLE
Specific users to authenticate

### ISSUE THREAD

**Issue by WolfyRed** [AuthMe/AuthMeReloaded#2345] opened 2021-06-01 00:53 UTC
**Is your feature request related to a problem? Please describe.**
I want many players to join without authenticating, because they aren't administrator accounts, but if administrator accounts do join, they need to authenticate.

**Describe the solution you'd like**
The solution I'd like is to have administrative accounts need to authenticate, or just an option for specific users to authenticate.

**Describe alternatives you've considered**
Making the plugin myself. Yeah I can't code in Java L

**Comment by ljacqu** [comment] 2021-06-01 08:39
Duplicate of #1387, in which I detail why I think this is an unnecessary addition

**Closed by ljacqu** 2021-06-01 08:39 UTC
Labels: Type: enhancement
