### ISSUE TITLE
Enforce login only for Opped players

### ISSUE THREAD

**Issue by matteoturini** [AuthMe/AuthMeReloaded#2476] opened 2022-01-06 18:38 UTC
### What feature do you want to see added?

I want a way to enforce login only for Opped players.

### Are there any alternatives?

Coding my own plugin.

**Comment by ljacqu** [comment] 2022-01-23 19:18
Duplicate of #1137

**Closed** 2022-01-23 19:18 UTC
Labels: Status: duplicate, Type: enhancement

**Comment by ljacqu** [comment] 2022-01-23 19:20
Sorry, #1387 is the right issue
