### ISSUE TITLE
easy dupping..

### ISSUE THREAD

**Issue by Eisenbahn** [AuthMe/AuthMeReloaded#721] opened 2016-05-24 03:09 UTC

**Comment by Eisenbahn** [comment] 2016-05-24 03:11
Simple get a friend, join the same time. There, two inventories. Then just open a chest, put it all you can, then the timeout will kick you. Everything placed in a chest, will keep there...

**Comment by Eisenbahn** [comment] 2016-05-24 03:14
Using the legacy 970 build (something like that) - but happens since older versions. java 7

**Comment by Eisenbahn** [comment] 2016-05-24 05:57
Been exploring more this bug. Player cant connect if Player is online. But if both login with Player nickname, and one login, both can do whatever they way.

**Comment by Eisenbahn** [comment] 2016-05-24 06:18
https://snag.gy/Nk6aHm.jpg

**Comment by Eisenbahn** [comment] 2016-05-24 06:35
But if both login with Player nickname AT THE SAME TIME*

**Comment by Eisenbahn** [comment] 2016-05-24 07:09
and cauldron

**Comment by Eisenbahn** [comment] 2016-05-24 18:43
It was 973. Sorry for constant messaging

**Comment by Eisenbahn** [comment] 2016-05-24 18:44
Using the Legacy jar

**Comment by sgdc3** [comment] 2016-05-24 20:26
Could you record a video, please? Probably it's an issue related to cauldron :/

**Comment by Eisenbahn** [comment] 2016-05-24 23:35
Well, kind of hard do this since i was not the one doing.

But not hard:
Both connect to the same server at the same time with the same name. If one of them login sucessfully, both could walk freely. So they can share same items in inventory dupping them :(

Maybe a check after a login for few seconds that check for two players with the same name? I noticed the name above its head is like Player, for both. But in tablist, they are like Player and Player93 (or other random number)

**Comment by sgdc3** [comment] 2016-06-15 01:15
Fixed in latest build

**Comment by sgdc3** [comment] 2016-06-15 01:15
@Eisenbahn

**Comment by Eisenbahn** [comment] 2016-06-15 01:15
Ok, will test it soon. []'s

**Comment by Eisenbahn** [comment] 2016-06-15 01:16
1130?

**Comment by sgdc3** [comment] 2016-06-15 01:17
yeah ;)

**Comment by Eisenbahn** [comment] 2016-06-21 16:55
Ello. Sorry for the delayed feedback.
Users claim that still possible to dupe using the method i said, two players in the same accounts, etc.


Using 1130
=/

**Comment by sgdc3** [comment] 2016-06-21 17:43
Any ideas @ljacqu @Gnat008 @DNx5 @games647

**Comment by games647** [comment] 2016-06-21 20:19
Do you have hideInventory enabled?

**Comment by Eisenbahn** [comment] 2016-06-21 23:24
I do have hideInventory enabled.

I got a custom plugins that checks for usernames. And its kind of working for me like that..

Im not sure if i have the source code, but im up to share this plugin jar with you guys.

[]'s

**Comment by Eisenbahn** [comment] 2016-06-29 07:29
Any news? Any way i could help?

**Comment by sgdc3** [comment] 2016-06-29 09:12
@games647 any idea?

**Comment by games647** [comment] 2016-06-29 09:22
@Eisenbahn Could you try to disable hideInventory? 

I don't think this is the cause, because first I already tested it against dupping and second the server should prevent that. Otherwise the client could always fake a inventory.

I think it's more a different inventory manipulation plugin or the server software itself.

**Comment by Eisenbahn** [comment] 2016-06-29 16:26
I've tried to disabled it, but still happens. That's why i enabled it. Trying to make it harder for duppers. =/

**Comment by games647** [comment] 2016-06-29 16:49
Do you have any inventory plugins installed?

**Comment by Eisenbahn** [comment] 2016-06-29 17:44
That does anything significatly, not that i can record.

Plugins (49): TuxTwoLib, WorldBorder, GroupManager, FrameProtect, RewardVoting, VoxelSniper, NoJoinMessage, SkinsRestorer, Sculptor, Quests, BossShop, RandomCommand, Vault, WardrobeGUI, CraftBay, ChestCommands, ProtocolLib, Votifier, OfflineMode, PwnFilter, WorldEdit, PokeMarket, VirtualPack, SpamStopper, WorldGuard, ItemSlotMachine, GlobalMarket, PwnPlantGrowth, PokeRandomizer, AutoAnnouncer, Simple_Suffix, Essentials, ServerSigns, EasyTrading, FramePicture, ServerListPlus, EnjinMinecraftPlugin, PlotSquared, InfoBoardReborn, CraftBook, EssentialsChat, EssentialsProtect, EssentialsSpawn, EssentialsAntiBuild, CS-CoreLib, MultiWorld, AuthMe, HolographicDisplays, CommandOverride

**Comment by games647** [comment] 2016-06-29 17:46
Then I guess it's a server software bug.

**Comment by Eisenbahn** [comment] 2016-06-29 17:48
Like cauldrons bug?
Any workaround? I got it 'safe' after i got this custom plugin..

**Comment by games647** [comment] 2016-06-29 17:48
No sorry. I'm out of ideas. Maybe the other could help.

**Comment by sgdc3** [comment] 2016-06-29 18:39
@Eisenbahn Can you try with only a clean cauldron installation and authme? (no mods, only authme as plugin)

**Comment by Eisenbahn** [comment] 2016-10-24 23:33
Sorry. Got a custom plugin that checks for double names online and kick them. I'm surviving like that. lol

**Comment by sgdc3** [comment] 2016-10-25 05:40
Still an issue then

**Comment by sgdc3** [comment] 2016-10-25 05:42
Could you try locally without the custom plugin and latest version of authme from our jenkins? (use the legacy jar)

**Comment by ljacqu** [comment] 2016-12-04 10:35
Hi @Eisenbahn

**Comment by Eisenbahn** [comment] 2016-12-04 12:40
I'm currently using 1242 build and stop updating after you guys changed the support to java 7 (i'm stuck in java 7)

**Comment by sgdc3** [comment] 2016-12-04 12:49
@Eisenbahn why are you stuck?

**Comment by Eisenbahn** [comment] 2016-12-04 12:54
Plugins, Mods, Custom Plugins and Custom Mods.

**Comment by sgdc3** [comment] 2016-12-04 12:55
it doesn't make sense, any java program written for java 7 work on 8 just fine.

**Comment by Eisenbahn** [comment] 2016-12-04 12:59
In theory, i suppost. Cause when i try it it breaks some stuff.

**Comment by sgdc3** [comment] 2016-12-04 13:27
very strange

**Comment by ljacqu** [comment] 2016-12-04 14:07
> any java program written for java 7 work on 8 just fine

But Eisenbahn said he's stuck on Java 7, and we switched to Java 8 ;) Other way around.

**Comment by sgdc3** [comment] 2016-12-04 14:53
@ljacqu Yeah, i know -_- He said that some plugin doens't work on java 8, but that doesn't make sense

**Comment by ljacqu** [comment] 2016-12-04 15:28
What are you on about? He says he's stuck with Java 7. https://github.com/Xephi/AuthMeReloaded/issues/721#issuecomment-264701650

> I'm currently using 1242 build and stop updating after you guys changed the support to **java 7 (i'm stuck in java 7**)

**Comment by Eisenbahn** [comment] 2016-12-05 02:08
I got a linux dedi and i whenever i switch the java version some plugins breaks, i dont know why.

**Comment by sgdc3** [comment] 2016-12-05 02:39
Could you list them?

**Closed** 2017-07-25 13:31 UTC
Labels: Status: no answer, Type: bug, Type: incompatibility
