### ISSUE TITLE
Unable to connect to MySQL

### ISSUE THREAD

**Issue by TheMixaDev** [AuthMe/AuthMeReloaded#2020] opened 2020-02-20 19:08 UTC
MySQL Config part: https://pastebin.com/8RhbXSxh , everything else in confing file is default
Console output: https://pastebin.com/tScGwbnq

My MySQL DB alive for years and properly working with connections via MySQL Workbench, PHP, .NET and J connectors.

Server: Spigot-1.8-R0.1-SNAPSHOT-latest.jar

AuthMe: 5.5.0

**Comment by MrMatttw** [comment] 2020-03-12 08:37
The same issue!
AuthMeReloaded version: 5.6.0
MySQL version: 8.0.17

**Comment by MrMatttw** [comment] 2020-03-12 08:40
Found the issue!
set the config.yml file the line for mySQLUseSSL as false:

**Comment by TheMixaDev** [comment] 2020-03-12 08:47
Already

**Comment by games647** [comment] 2020-03-13 10:07
Duplicate of #1779

**Closed by games647** 2020-03-13 10:07 UTC
Labels: Type: bug
