### ISSUE TITLE
Latest version 1.14.4

### ISSUE THREAD

**Issue by Dragsio** [AuthMe/AuthMeReloaded#1946] opened 2019-11-30 15:09 UTC
When will the latest version 1.14.4 be released? This version does not work for 1.14.4.

**Comment by AnVir** [comment] 2019-12-06 16:11
Confirmed and very highly requested - please, do an update!
The plugin tells that 
```
[19:58:42] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2336
[19:58:42] [Server thread/WARN]: [AuthMe] You are running an unsupported server version!AuthMe requires Spigot 1.8.X or later!
[19:58:42] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
```
And it looks like rude lie - WTH, I have not defined anything like that in config!!
Please at least allow to use plugin with more recent versions it knows - there is a chance it just will work flawless after next update. Maybe, protect that feature with an option.

Please. We are waiting.

**Comment by krusic22** [comment] 2019-12-06 17:44
The 1.14.4 version is already out. Use the latest version from the build server / Jenkins.

**Comment by AnVir** [comment] 2019-12-07 00:42
As you can see, my quote contains build number and as I see, it's this very version you mean, isn't it?
https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/lastSuccessfulBuild/

**Comment by ljacqu** [comment] 2019-12-08 19:04
I think we can close this:
@Dragsio Please grab a newer build at https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/ . With Spigot 1.14.4 it seems to work fine (tested both MySQL & SQLite)

@AnVir, you're getting the message not because of 1.14.4 but because you're using CraftBukkit or some other derivative that isn't based on Spigot. We require Spigot.

> And it looks like rude lie - WTH, I have not defined anything like that in config!!

Oof, it's the setting "Security.SQLProblem.stopServer". It's the most reasonable behavior for an authentication plugin(!) to shut down if it notices it couldn't start... After all the workaround is quite simple (disabling the plugin, thus confirming it's really desired not to have it anymore)

**Closed by ljacqu** 2019-12-08 19:04 UTC

**Comment by Wixent** [comment] 2020-01-05 03:59
@ljacqu I have the same issue and im using Spigot 1.14.4 D:

**Comment by ljacqu** [comment] 2020-01-05 17:54
Please update to the latest build (see link in above comment) and if the error persists, report a new bug following the template
