### ISSUE TITLE
Little delay for Authme's motd

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1115] opened 2017-03-01 12:14 UTC
When we join a server with AuthmeBridge, the motd is sent before the join message. For this reason, I would like that you add a little delay before sending the motd.

E.g.
Current situation: 

> MOTD
> [+] Twonox

Wanted situation:

> [+] Twonox
> MOTD

**Comment by ljacqu** [comment] 2017-12-09 11:14
Duplicate of #1042

**Closed by ljacqu** 2017-12-09 11:14 UTC
Labels: Type: enhancement
