### ISSUE TITLE
jpremium converter

### ISSUE THREAD

**Issue by diocan** [AuthMe/AuthMeReloaded#2680] opened 2023-02-01 16:08 UTC
### What behaviour is observed?

hi i have need to convert jpremium(sha256 mysql) in authme (sha256) but is very difficult to do

### Expected behaviour

https://github.com/AuthMe/AuthMeReloaded/wiki/Converters mysql to sql

### To Reproduce

https://github.com/AuthMe/AuthMeReloaded/wiki/Converters

### Plugin list

a lot

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

latest beta-2

### Error log (if applicable)

its work but dont carry the username and password

### Configuration

https://gist.github.com/diocan/638fa8fbe3685ffa8e3c6b03cf742451

**Comment by ljacqu** [comment] 2024-01-02 16:38
Duplicate of #2500

**Closed by ljacqu** 2024-01-02 16:38 UTC
Labels: Type: enhancement
