### ISSUE TITLE
lagggg my server

### ISSUE THREAD

**Issue by FlexVN** [AuthMe/AuthMeReloaded#1289] opened 2017-07-20 09:15 UTC
### What behaviour is observed:
What happened?

### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by FlexVN** [comment] 2017-07-20 09:16
my errors: https://www.hastebin.com/fehariyaza.md
my config: https://www.hastebin.com/kizanuzogu.bash
and: errors [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
[15:54:49] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Start completed.

**Comment by games647** [comment] 2017-07-20 09:19
AuthMe cannot connect to your MySQL server. If this happens on startup please verify your settings.

**Comment by FlexVN** [comment] 2017-07-20 09:24
It has links to the mysql server. The player can still log in, but after a while it clears the server.

**Comment by FlexVN** [comment] 2017-07-20 09:47
INFO fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
how to fix?

**Comment by DNx5** [comment] 2017-07-21 13:58
duplicate of #1292

**Closed by DNx5** 2017-07-21 13:58 UTC
Labels: Status: duplicate
