### ISSUE TITLE
Description of how to setup this properly with Auth server and Lobby server

### ISSUE THREAD

**Issue by Baterka** [AuthMe/AuthMeReloaded#2207] opened 2020-10-04 17:06 UTC
Hi, Is there anyone who can describe for me (and possible for others) how to properly setup AuthMe and AuthMeBungee to achieve following behavior?

**Servers:**
- Bungeecord Proxy - AuthMeBungee installed
- Spigot "Auth" - AuthMe installed
- Spigot "Lobby" - possibly AuthMe installed? (But dont login again!)
- Other Spigot servers like "Survival", "Skyblock", "Bedwars", ...

**Workflow:**
1. Player connect to network
2. Player is connected to "auth" server and he need to do /login (or he is logged by FastLogin plugin because he original Minecraft)
3. Player is automatically redirected to 'lobby' server (No need to do /login again!)
4. Player can use /changepassword, /unregister, /email commands on lobby server
5. Player can switch to other servers without ever logging again

How to achieve this? 
My current status is, that players are unable to change password or set email for refresh, because they are redirected after login from "auth" server.

I started writing bungeecord plugin to forward /changepassword command to auth server, but I realized its very hard to do.
For example BungeeMessaging need at least one player connected to server, Redis and WebServer are stupid overkill.
It can be made, that 'lobby' server also have AuthMe installed and player is logged automatically, but I was unable to achieve this.

**Comment by ljacqu** [comment] 2020-10-05 18:20
Duplicate of https://github.com/AuthMe/AuthMeBungee/issues/77

**Closed by ljacqu** 2020-10-05 18:20 UTC
Labels: Type: enhancement
