### ISSUE TITLE
Unregistered players don't see their inventory

### ISSUE THREAD

**Issue by DutchUser** [AuthMe/AuthMeReloaded#1443] opened 2017-12-05 13:33 UTC
### What behaviour is observed:
After i edited the config i got issue in the server. Players that not registered see multple times an empty inventory till they open an chest.

### What behaviour is expected:
Well... Not that they can not see there inventory.

### Steps/models to reproduce:
1, kopie and past my config: https://pastebin.com/7WsC3Vuy
2, Let an **un-registered** player join.
3, You dont see you inventory till you open an chest. 

### Plugin list:
Does not apply, Its caused by editing the config.

### Environment description
Does not apply

### AuthMe build number:
Version: AuthMeReloaded v5.4.0 (build: 1877)

### Error Log:
No any errror. Not after startup or reloading.

### Configuration:

https://pastebin.com/7WsC3Vuy

**Comment by sgdc3** [comment] 2017-12-05 15:26
Could you please explain your environment? (server version, plugin list, etc...)

**Comment by DutchUser** [comment] 2017-12-05 15:43
As i said about the plugins, It does not matter what for plugins are on the server. With an Fresh config where **only** the force login is turned off it workes fine. But after i also change other things to false the plugin decide to be annoying. 

Servert version: Spigot 1.12.2

But sure. If you still wnna know the plugin list: https://pastebin.com/imfpuY6r

**Comment by DutchUser** [comment] 2017-12-05 15:56
I found a bit of an Fix for it. If the inventory protection is turned off. This will not happen. So is this maybe an "inventory protect" section bug?

**Comment by DutchUser** [comment] 2017-12-05 15:59
You can maybe "reproduce" it by

- Turn off the force register.
- Turn on the inventory protection.
- Log in with an not registered account.

**Comment by Kongolan** [comment] 2019-06-07 12:35
Still present in Build #2256 (Tue Jun 04). The ProtcolLib adapter just doesn't check for the force registration feature and doesn't check for unregistered players properly. THIS NEEDS REWORK.

**Comment by ljacqu** [comment] 2019-06-22 21:37
Hi @DutchUser , thanks for the report! We've revised the behavior based also on the issue above and you're welcome to check it with the latest dev build at https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
I'll mark this as a duplicate of #1830 just for our book keeping purposes but we'd really look forward for your feedback, preferably in #1830.

**Closed by ljacqu** 2019-06-22 21:37 UTC
Labels: Type: bug
