### ISSUE TITLE
remove speed feature broken on 1.12

### ISSUE THREAD

**Issue by l89669** [AuthMe/AuthMeReloaded#1222] opened 2017-05-21 13:15 UTC
server: latest spigot & waterfall
authme: latest on CI, version spigot( version legacy does not have this problem)
what happed: player has no speed after login( use /speed 1 can fix this )

**Comment by Jamaic230** [comment] 2017-05-21 13:20
Something like that happens on 1.11 too, after user logs in, sometimes his speed is still 0, so he can't walk, but he can jump. I stopped using this feature, I instead use "allowMovement: true" with "allowedMovementRadius: 1".
I think it happens when user, which is not logged in (therefore having speed 0) disconnects, some plugin remembers this last speed, which is then enforced after player logs in next time.

**Comment by sgdc3** [comment] 2017-05-21 16:50
Could you try to set limbo.restoreFlySpeed to RESTORE_NO_ZERO

**Comment by Twonox** [comment] 2017-06-02 21:19
@l89669 
Do you have `useAsyncTasks: true` ?

**Comment by lianera** [comment] 2017-06-11 08:31
Same issue but not frequently. I also found if the player manually use the command 'logout' and then disconnect and relogin, the problem always happen.

**Comment by ljacqu** [comment] 2017-06-11 09:06
@lianera that's helpful to know, thank you. Am I right to assume your version is >= 5.3.0?

**Comment by lianera** [comment] 2017-06-11 11:00
@ljacqu Yes, I used 'AuthMe-5.3.1-spigot.jar' , and the console showed the version is 'AuthMeReloaded v5.3.1 b1702'.

**Comment by sgdc3** [comment] 2017-07-02 23:08
@l89669 @Jamaic230 @Twonox @lianera Does it happen with latest dev builds? http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by ljacqu** [comment] 2017-07-03 06:50
Duplicate of #1238 (just linking the issues, don't mind me ;))

**Comment by l89669** [comment] 2017-07-03 07:20
@sgdc3 not tested yet. But as I have test before, the legacy jar does not have this problem

**Comment by sgdc3** [comment] 2017-07-06 23:57
@l89669 Any news?

**Closed** 2017-07-08 21:36 UTC
Labels: Status: no answer, Type: bug
