### ISSUE TITLE
I need MongoDB Support

### ISSUE THREAD

**Issue by bckd00r** [AuthMe/AuthMeReloaded#2344] opened 2021-05-30 18:52 UTC
Hello, I want MongoDB support for my server.

More accessible databases and user interface with MongoDB

This is a really necessary feature. I hope you add an easily usable MongoDB support. I love you guys <3

**Comment by ljacqu** [comment] 2021-05-31 06:48
Thanks for the kind words. Closing as a duplicate of #2096

**Closed by ljacqu** 2021-05-31 06:48 UTC
Labels: Type: enhancement
