### ISSUE TITLE
BungeeCord problem

### ISSUE THREAD

**Issue by Mgazul** [AuthMe/AuthMeReloaded#1193] opened 2017-05-01 08:01 UTC
BungeeCord Server, the player landing, can not move, can only jump, where is the wrong?

**Comment by Twonox** [comment] 2017-05-01 10:41
What version of Authme do you use ?

**Comment by Mgazul** [comment] 2017-05-08 21:48
5.3

**Comment by sgdc3** [comment] 2017-05-09 05:41
Could you post your plugin list?

**Comment by Mgazul** [comment] 2017-05-10 03:45
https://ooo.0o0.ooo/2017/05/10/59128cb9e11d4.png

**Comment by sgdc3** [comment] 2017-05-10 09:21
@Mgazul could you try to disable sessions?

**Comment by Twonox** [comment] 2017-05-10 11:47
Mgazul, what is your servers version ? Your authme's build number ? And, please, send us your full authme's config.

Next time, provide us directly more informations please.

**Comment by Mgazul** [comment] 2017-05-10 18:38
I was set up like this: bungeeCord ---> spigot (AuthMe)
AuthMe Version:-SNAPSHOT-b1644
server is running CraftBukkit version git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
BungeeCord  #1231
authme's config in Attachment
[``](https://github.com/PFCraft/PFCraft-BC/blob/master/config.yml)

**Comment by Twonox** [comment] 2017-05-10 19:04
Thanks.
Your walk/fly speed is it restored on login if you set it to 1 with essentials command (/speed) before disconnect ?
Try to set `restoreFlySpeed: 'DEFAULT'` and `restoreWalkSpeed: 'DEFAULT'`

**Comment by Mgazul** [comment] 2017-05-10 20:25
About 5 days ago I set up is: allowMovement: true ，Unregistered players can move around，This solves the problem of moving the player；But I do not want that，I am much like to know what this is causing
As for the first method you just had, I did not use the necessities, the second method I modified, waiting for more players online test, I will reply to you!

**Comment by Twonox** [comment] 2017-05-10 20:51
Don't forget to set `allowMovement: false`
If I understand well, only new players have the walk issue (after register) ?

**Comment by Mgazul** [comment] 2017-05-10 21:43
No！New players do not have this problem, the problem appears in the old players

**Comment by TheMindaugas** [comment] 2017-05-12 12:17
Try using my client, as far as I've tested it's working properly.
https://www.spigotmc.org/resources/gateway-authme-bungeecord-client-for-bukkit-spigot.40151/

**Comment by Twonox** [comment] 2017-05-12 14:38
@TheMindaugas There is no relationship with your plugins.

**Comment by sgdc3** [comment] 2017-05-12 14:45
@ljacqu I would like to delay the 5.3 release and fix this first, probably we changed something in session that breaks the login process on a second instance

**Comment by ljacqu** [comment] 2017-05-12 16:55
@sgdc3 Fine by me if we can release in two weeks? Sun 28.5. for example

**Comment by sgdc3** [comment] 2017-05-12 20:00
@ljacqu Yeah, that would be fine ;)

**Comment by sgdc3** [comment] 2017-05-21 12:47
@ljacqu ok we need to fix this qnd we are ready to release ;)

**Comment by ljacqu** [comment] 2017-05-21 12:59
@sgdc3 Excellent, will you have time to look at this? I have no knowledge or interest in Bungeecord.

Reading this:

> No！New players do not have this problem, the problem appears in the old players

makes me think we may have had an issue with our limbo player system we have since solved. Thus, old players who were affected by the bug have walk speed 0, which AuthMe will never change.

**Comment by sgdc3** [comment] 2017-05-21 13:26
@ljacqu Not ATM, currently i'm preparing for some important exams, i'll be way more active this summer.

**Comment by ljacqu** [comment] 2017-05-28 17:03
It's May 28th, I'm moving this to the next milestone.

**Comment by sgdc3** [comment] 2017-09-30 14:06
The issue was probably caused by some old glitch, not bungeecord related

**Closed by sgdc3** 2017-09-30 14:06 UTC
Labels: Topic: bungeecord
