### ISSUE TITLE
Error in XFBCRYPT

### ISSUE THREAD

**Issue by RoffDaniel** [AuthMe/AuthMeReloaded#1826] opened 2019-06-03 15:25 UTC
### What behaviour is observed:
Registration does not work correctly

### What behaviour is expected:
I had to register, and automatically log in. But, after entering the data an error occurs... Everything is on video.

### Plugin list:
CoreProtect, WorldEdit, OpenInv, betterSleeping, PermissionsEx, EasyWhitelist, Vault, MySkin, ProtocolLib, WorldGuard, Essentials, TradePlus, TAB, ChatEx, ActionHealth, EssentialsSpawn, AuthMe

### Environment description
MySql

### AuthMe build number:
2248

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

### Configuration:
https://pastebin.com/PaApHixZ and Video (https://youtu.be/hD56gu4L5v8)

**Comment by sgdc3** [comment] 2019-06-04 09:57
What's the message that is sent you by the server when you try to register?

**Comment by RoffDaniel** [comment] 2019-06-04 11:31
Error during SQL operation: duplicate entry ‘1’ for key ‘primary’
Error during SQL operation: duplicate entry ‘roffdaniel’ for key ‘username_lower’

**Comment by ljacqu** [comment] 2019-06-17 20:05
Essentially—and you won't like this answer—this is a duplicate of #1468, which tracks the proper integration of Xenforo into AuthMe.

We have people bumping that issue from time to time but no one has been able to provide us the answers we need in order to integrate it. Last I heard it's possible to register in Xenforo and then play in Minecraft. For a proper integration we need someone that can tell us step by step which entries have to be made into the database. The source code is not available and so we're blind.

**Closed by ljacqu** 2019-06-17 20:05 UTC
Labels: Type: bug
