### ISSUE TITLE
Too many channels registered

### ISSUE THREAD

**Issue by Eufranio** [AuthMe/AuthMeReloaded#967] opened 2016-10-03 22:30 UTC
When a player disconnects, the console spams a error :

```
[00:25:17 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Too many channels registered
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [PaperSpigot.jar:git-Paper-819]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalStateException: Too many channels registered
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1181) ~[PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2545) ~[PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[PaperSpigot.jar:git-Paper-819]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[PaperSpigot.jar:git-Paper-819]
        ... 5 more
[00:25:17 INFO]: Sr_Haron lost connection: Disconnected
[00:25:17 INFO]: Sr_Haron saiu do Lobby
```

Using BungeeCord with MySQL

**Comment by sgdc3** [comment] 2016-10-03 22:33
Are you sure the cause is authme?

**Comment by sgdc3** [comment] 2016-10-03 22:34
It is a generic exception, have you tested without authme?

**Comment by Eufranio** [comment] 2016-10-03 22:37
Yes, happened after update Authme, and I have only Authme and FastLogin on that server (I reported first here, but I can report to FastLogin if you prefer)

**Comment by sgdc3** [comment] 2016-10-03 22:39
@games647

**Comment by games647** [comment] 2016-10-04 09:37
@Eufranio Do you reloaded the server?

The error is about plugins channels. You reached the maximum amount of 128 channels. Channels are used for server-player communication or in the case of BungeeCord spigot-bungee communication.

Example channels:
FastLogin - one channel -> with the plugin name
BungeeCord 
Minecraft
Forge - FML channel

AuthMe communicates just over BungeeCord one and doesn't need to register an addition one.

The best idea to investigate this is to look what are all the channels which are tried to be registered.

With ProtocolLib
/packet add client 63 true

and try again.

**Comment by Eufranio** [comment] 2016-10-08 13:14
I did a lot of testing, seems that I was using an older version of PaperSpigot.

**Comment by sgdc3** [comment] 2016-10-08 18:43
@Eufranio Fine, thank you ;)

**Comment by Eufranio** [comment] 2017-01-08 03:15
The problem is back. What should I see? With this command , I don't see any error, only a spam with
```
[21:14:39 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Duuh_Stark:
{ a = "AuthMeBridge", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 25, cap: 25/25)" } }
[21:14:39 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Duuh_Stark:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 1, cap: 1/1)" } }
[21:14:39 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Duuh_Stark:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 44, cap: 44/44)" } }
[21:14:39 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to MalenaDebi:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[21:14:40 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Duuh_Stark:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 14, cap: 14/14)" } }
[21:14:40 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to MalenaDebi:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[21:14:41 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to MalenaDebi:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[21:14:42 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to MalenaDebi:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[21:14:43 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to MalenaDebi:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
```

**Comment by sgdc3** [comment] 2017-01-08 03:51
@games647

**Comment by ljacqu** [comment] 2017-01-08 07:19
@Eufranio In the future, please open a new issue when something comes back months apart. Thanks :)

**Comment by Eufranio** [comment] 2017-01-08 07:26
Even if it's duplicate?

**Comment by games647** [comment] 2017-01-08 09:25
@Eufranio We need the register messages or when the error occurs. This should happen when the player logs in.

**Comment by ljacqu** [comment] 2017-01-08 10:43
@Eufranio It's just a minor comment I mentioned mostly because this was closed a few months ago. Since then we've done many changes so it's arguably not a "duplicate" anymore because the cause might be quite different.
It would be especially "problematic" (I'm being a bit dramatic :wink:) if we commit changes for this issue and close it within a milestone and then close the milestone. This is of course not the case here. :smile:

**Comment by Eufranio** [comment] 2017-01-09 01:45
```
[19:44:15 INFO]: UUID of player Denis_Mad is d9e08e17-41d0-40c3-bd92-5cf2ca6e4ae7
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "REGISTER", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 100, cap: 100/100)" } }
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "MC|Brand", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 7, cap: 256)" } }
[19:44:15 INFO]: Denis_Mad[/201.2.44.217:38598] logged in with entity id 287 at ([Spawn]86.49537870467617, 83.0, 344.51829977273843)
[19:44:15 INFO]: Creating empty config: /home/frani/Lobby/plugins/Essentials/userdata/d9e08e17-41d0-40c3-bd92-5cf2ca6e4ae7.yml
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 17, cap: 17/17)" } }
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "FastLogin", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to PiskeBR:{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 14, cap: 14/14)" } }
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:15 INFO]: [AuthMe] Denis_Mad logged in!
[19:44:15 INFO]: + Denis_Mad ~ Brazil
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "AuthMeBridge", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 24, cap: 24/24)" } }
[19:44:15 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 1, cap: 1/1)" } }
[19:44:16 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 44, cap: 44/44)" } }
[19:44:16 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:16 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Too many channels registered
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Too many channels registered
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1076) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2504) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        ... 5 more
[19:44:16 INFO]: [AuthMe] Denis_Mad logged in!
[19:44:16 INFO]: + Denis_Mad ~ Brazil
[19:44:16 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "AuthMeBridge", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 24, cap: 24/24)" } }
[19:44:17 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to Denis_Mad:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 14, cap: 14/14)" } }
[19:44:17 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:18 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:19 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:19 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Too many channels registered
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Too many channels registered
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1076) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2504) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[PaperSpigot.jar:git-Spigot-de459a2-51263e9]
        ... 5 more
[19:44:20 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:20 INFO]: [AuthMe] heromamghg logged in!
[19:44:20 INFO]: + heromamghg ~ Brazil
[19:44:20 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "AuthMeBridge", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 25, cap: 25/25)" } }
[19:44:21 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:22 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to heromamghg:
{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 9, cap: 9/9)" } }
[19:44:23 INFO]: UUID of player VWFinal is f802feeb-01ea-48f1-9e7c-055cf200522c
[19:44:23 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to VWFinal:{ a = "REGISTER", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 100, cap: 100/100)" } }
[19:44:23 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to VWFinal:{ a = "MC|Brand", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 7, cap: 256)" } }
[19:44:23 INFO]: VWFinal[/186.236.108.196:52933] logged in with entity id 289 at ([Spawn]86.49537870467617, 83.0, 344.51829977273843)
[19:44:23 INFO]: Creating empty config: /home/frani/Lobby/plugins/Essentials/userdata/f802feeb-01ea-48f1-9e7c-055cf200522c.yml
[19:44:23 INFO]: heromamghg issued server command: /servidores
[19:44:23 INFO]: [ProtocolLib] Sent PacketPlayOutCustomPayload[24, legacy: 63] to VWFinal:{ a = "BTLP", b = { a = "UnpooledHeapByteBuf(ridx: 0, widx: 17, cap: 17/17)" } }
```

**Comment by games647** [comment] 2017-01-09 08:46
Sadly the content of the register message is a byte array. Therefore it has to be transformed into a String (text). This requires an extra modification (i.e. small debug plugin hooking into ProtocolLib).

Maybe "BTLP" is registering too many channels

**Closed** 2017-07-27 19:59 UTC
Labels: Status: not our fault, Topic: bungeecord

**Comment by LengFish** [comment] 2025-05-09 11:06
I had this problem when I was in BungeeCord. When I modified the upper limit of channels, this problem was solved. I hope it will help you.
