### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by Scorbunny10** [AuthMe/AuthMeReloaded#2773] opened 2024-01-02 16:20 UTC
### What feature do you want to see added?

Countdown on action bar or bossbar which is countdown to kick if you not log in.

### Are there any alternatives?

I looking for the addon for authme but I don't find countdown

**Comment by ljacqu** [comment] 2024-01-02 16:37
Duplicate of  #2259

**Closed by ljacqu** 2024-01-02 16:37 UTC
Labels: Type: enhancement
