### ISSUE TITLE
Suggestion for modification

### ISSUE THREAD

**Issue by flipper1406** [AuthMe/AuthMeReloaded#1363] opened 2017-10-17 18:57 UTC
Hi,

i recently had the problam that my server stopped itself because of a bad config. (My fault)

My suggestion is a hint in the log, that the server is restarting because of AuthMe as I haven´t found a hint at all, just the message that the server stops.
Makes it a bit easier for other serverowner I guess.

flipper1406

**Comment by ljacqu** [comment] 2017-10-17 19:25
Hi, how did you notice that it was a bad config? Maybe a copy of your log would still help us pinpoint the cause.

**Comment by flipper1406** [comment] 2017-10-17 20:13
I changed the following settings:

    # What type of database do you want to use?
    # Valid values: SQLITE, MYSQL
    backend: 'SQLITE'
    # Enable database caching, should improve database performance
    caching: true
    # Database host address
    mySQLHost: '127.0.0.1'
    # Database port
    mySQLPort: '3306'
    # Connect to MySQL database over SSL
    mySQLUseSSL: true
    # Username to connect to the MySQL database
    mySQLUsername: 'authme'
    # Password to connect to the MySQL database
    mySQLPassword: '12345'
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: 'authme'
    # Table of the database
    mySQLTablename: 'authme'
    # Column of IDs to sort data
    mySQLColumnId: 'id'
    # Column for storing or checking players nickname
    mySQLColumnName: 'username'
    # Column for storing or checking players RealName
    mySQLRealName: 'realname'
    # Column for storing players passwords
    mySQLColumnPassword: 'password'
    # Column for storing players emails
    mySQLColumnEmail: 'email'
    # Column for storing if a player is logged in or not
    mySQLColumnLogged: 'isLogged'
    # Column for storing players ips
    mySQLColumnIp: 'ip'
    # Column for storing players lastlogins
    mySQLColumnLastLogin: 'lastlogin'

I changed those to the connection of a MYSQL database but I didn´t changed >> backend: 'SQLITE' << and therefore the database couldn´t be found.

Here the lines from my log:

[16:10:13] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.3.2-b1726

Okay by searching all messages by Authme I now found the following lines:

[16:10:29] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[16:10:29] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[16:10:29] [Server thread/INFO]: [AuthMe] AuthMe 5.3.2-b1726 disabled!

Then I just didn´t payed attention enough.
I just saw several lines later the following:

[16:10:30] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:10:30] [Server thread/INFO]: Done (16.795s)! For help, type "help" or "?"
[16:10:30] [Server thread/INFO]: Stopping server

But as there is the message my suggestion is already implemented.

**Comment by ljacqu** [comment] 2017-10-17 20:21
I think it's the best we can do, unfortunately, since as soon as the plugin shuts down we don't have a chance to log anything anymore (like at the very end to really catch the user's attention). Thanks for the ticket, nevertheless. I'll go ahead and close this.

**Closed by ljacqu** 2017-10-17 20:21 UTC
