### ISSUE TITLE
AuthMe > OP Player names can chat before /login

### ISSUE THREAD

**Issue by rmellis** [AuthMe/AuthMeReloaded#1858] opened 2019-07-07 20:34 UTC
### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
Running 1x jar of Build #2273 (Sun Jul 07 17:00:51 UTC 2019)

### What behaviour is observed:
When a player logges in with a staff player name who is OP'd they are able to send messages in chat before the /login process

### What behaviour is expected:
Messages of all players not to apear in chat before login

### Steps/models to reproduce:
The UserName of the Player being that of an OP's player

### Plugin list:
This can be found by running `/pl`
 Plugins (40): ActionHelth, AdvancedBan, AsyncWorldEdit, AuthMe, AuthMeTitle, BarAPI, Citizens, ClearLag, commandhook, commandNPC, CoreProtect, DeilyRewards, DeathMessagesPrime, DeluxMenus, DiscordSRV, DynMap, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsXMPP, Factions, FloydBot, FeatherBoard, GroupManager, Matrix, MCJobs, mcMMO, Multiverse-core, NoProxyFree, OldCombatMechanics, PocketGames, ProtocolSupport, QuickShop, SkinsRestorer, Vault, ViaVersion, VoxelSniper, WeatherNews, WorldEdit, WorldGuard

### Environment description
Paper version git-Paper-626 (MC: 1.13.2)

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2273)
I've tried some random slightly older builds too and had the same issue

### Error Log:
N/A
### Configuration:
[https://paste.ubuntu.com/p/m74gshjtSt/](https://paste.ubuntu.com/p/m74gshjtSt/)

**Comment by krusic22** [comment] 2019-07-07 20:38
Duplicate of #1810.

**Comment by ljacqu** [comment] 2019-08-02 15:10
As written in the issue that krusic22 marked:

> Just negate the "authme.allowchatbeforelogin" permission to users with *

**Closed by ljacqu** 2019-08-02 15:10 UTC
