### ISSUE TITLE
[Bug] The session will never expire after the server reboot

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [AuthMe/AuthMeReloaded#1674] opened 2018-10-30 01:27 UTC
Just that.
When the server reboot, the session of the player expire and he need to type his password again.
The session should only expire if the player's ip changes or if the player join with another nick and same ip.

It would be nice if AuthMe was more oriented to a web page login system.
Example: in facebook you do not have to write your password all the time, your information is stored in the browser.

"Forgot my password" player problem?
Support from the staff and "/email add" command = solution

**Comment by ljacqu** [comment] 2018-10-30 06:35
Duplicate of #1650

**Comment by 7wOv6ySCjo** [comment] 2018-10-30 13:06
I do not think this is a duplicate of #1650 
Player session's works fine for me.
I'm just asking if they could add the feature that the session never expires, even if the server restarts.

Something like this:

> settings:
>     sessions:
>         # Do you want to enable the session feature?
>         # If enabled, when a player authenticates successfully,
>         # his IP and his nickname is saved.
>         # The next time the player joins the server, if his IP
>         # is the same as last time and the timeout hasn't
>         # expired, he will not need to authenticate.
>         enabled: true
>         # After how many minutes should a session expire?
>         # A player's session ends after the timeout or if his IP has changed
>         timeout: 0 # 0 mean session never expire
>         keepSessionAfterServerReboot: true

**Comment by ljacqu** [comment] 2018-10-30 20:55
But this should already work by a mix of `hasSession` and `lastLogin` in the database. What's your config.yml?

**Comment by 7wOv6ySCjo** [comment] 2018-11-02 16:21
You were right, this is a duplicate of #1650 
Session is not working properly.
Sometimes it works other times not and I think I found the reason.

Start a fresh Spigot 1.8.8 server with only the AuthMe plugin.
https://i.gyazo.com/e432cf56645ccd3cb66730b7e00f6939.png
https://i.gyazo.com/3cc11a79246df7be3087f3ad877ec691.png

Spigot Version: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
AuthMe Version: AuthMeReloaded v5.5.0-SNAPSHOT (build: 2153)
Server is in offline mode.

Only i change 3 settings in config.yml

> settings:
>     sessions:
>         # Do you want to enable the session feature?
>         # If enabled, when a player authenticates successfully,
>         # his IP and his nickname is saved.
>         # The next time the player joins the server, if his IP
>         # is the same as last time and the timeout hasn't
>         # expired, he will not need to authenticate.
>         enabled: true
>         # After how many minutes should a session expire?
>         # A player's session ends after the timeout or if his IP has changed
>         timeout: 1440

> maxRegPerIp: 0

> logLevel: DEBUG

For testing.

Enter with nick: md_5 and sessions work fine.
Enter with nick: Xephi and sessions don't work. 
md_5 it has lowercase only.
Xephi has a capital letter.
Session only seems to work well with nicks that are written in lowercase.
AuthMe saves the nicknames in lowercase only, that is why the session never corresponds.

**Comment by ljacqu** [comment] 2018-12-04 17:38
I'm currently investigating the bug at #1650 and will close this as a duplicate just to make our issue tracker clearer. Please continue conversations there for the bug of "session doesn't work for name with caps". 
The first post mentions about having a 2fa only if the ip address changes, this is to be handled within #1525.

**Closed by ljacqu** 2018-12-04 17:38 UTC
Labels: Type: bug
