### ISSUE TITLE
Xenforo support issues

### ISSUE THREAD

**Issue by vanthoi** [AuthMe/AuthMeReloaded#957] opened 2016-09-29 18:34 UTC
How to configure the supported databases from xenforo.
I have a forum. There are many active members in the forum. Is there any way I can use the user account directly from the databases of xenforo. I have read through a lot of Authme information. But I have yet to find a way for me to manually configure it.  You can are taking time to guide me a few basic steps are not?

Thank you!

**Comment by sgdc3** [comment] 2016-09-29 21:42
Atm out xenforo integration has some issues, we'll try to solve them ASAP.

**Comment by vanthoi** [comment] 2016-09-30 04:49
You are facing the problems of xenforo. I can help with your this source code on xenforo!

**Comment by sgdc3** [comment] 2016-09-30 11:32
That would be very useful ;)

**Comment by ljacqu** [comment] 2016-09-30 13:17
That would really be cool :) The state right now, taken from https://github.com/Xephi/AuthMeReloaded/issues/137#issuecomment-241244136:

> I think this is almost done, what still doesn't work is that a user cannot log into the website when he registers via AuthMe.

> If everything else works, we need to know what needs to be written into the database additionally. Unfortunately, as long as no one can tell us what it is and we don't have access to the Xenforo source, we're blind.

So two things are not yet answered:
- Does everything besides in-game registration work?
- What do we need to write additionally in the database to make players able to log into Xenforo when they register in Minecraft?

**Comment by vanthoi** [comment] 2016-09-30 14:52
I have code from file register of xenforo:

`
	/**
	 * Registers a new user.
	 *
	 * @return XenForo_ControllerResponse_Abstract
	 */
	public function actionRegister()
	{
		$this->_assertPostOnly();
		$this->_assertRegistrationActive();

		$inputData = $this->_getRegistrationInputData();
		$data = $inputData['data'];
		$passwords = $inputData['passwords'];
		$customFields = $inputData['customFields'];
		$customFieldsShown = $inputData['customFieldsShown'];
		$errors = $inputData['errors'];

		$options = XenForo_Application::getOptions();

		if (!XenForo_Captcha_Abstract::validateDefault($this->_input))
		{
			$errors[] = new XenForo_Phrase('did_not_complete_the_captcha_verification_properly');
		}

		if (XenForo_Dependencies_Public::getTosUrl() && !$this->_input->filterSingle('agree', XenForo_Input::UINT))
		{
			$errors[] = new XenForo_Phrase('you_must_agree_to_terms_of_service');
		}

		$writer = XenForo_DataWriter::create('XenForo_DataWriter_User');
		if ($options->registrationDefaults)
		{
			$writer->bulkSet($options->registrationDefaults, array('ignoreInvalidFields' => true));
		}
		$writer->bulkSet($data);
		$writer->setPassword($passwords['password'], $passwords['password_confirm'], null, true);

		// if the email corresponds to an existing Gravatar, use it
		if ($options->gravatarEnable && XenForo_Model_Avatar::gravatarExists($data['email']))
		{
			$writer->set('gravatar', $data['email']);
		}

		$writer->set('user_group_id', XenForo_Model_User::$defaultRegisteredGroupId);
		$writer->set('language_id', XenForo_Visitor::getInstance()->get('language_id'));

		$writer->setCustomFields($customFields, $customFieldsShown);

		if (!$this->_validateBirthdayInput($writer, $birthdayError))
		{
			$errors[] = $birthdayError;
		}

		$registerTime = XenForo_Application::getSession()->get('registrationTime');
		if (!$registerTime || ($registerTime + $options->get('registrationTimer')) > time())
		{
			$errors[] = new XenForo_Phrase('sorry_you_must_wait_longer_to_create_account');
		}

		$regKey = XenForo_Application::getSession()->get('registrationKey');
		if (!$regKey  || $regKey != $this->_input->filterSingle('reg_key', XenForo_Input::STRING))
		{
			$errors[] = new XenForo_Phrase('something_went_wrong_please_try_again');
		}

		$spamModel = $this->_runSpamCheck($writer, $errors);

		$writer->advanceRegistrationUserState();
		$writer->preSave();

		$errors = array_merge($errors, $writer->getErrors());

		if ($errors)
		{
			$fields = $data;
			$fields['tos'] = $this->_input->filterSingle('agree', XenForo_Input::UINT);
			$fields['custom_fields'] = $customFields;
			return $this->_getRegisterFormResponse($fields, $errors);
		}

		$writer->save();

		$user = $writer->getMergedData();

		$spamModel->logSpamTrigger('user', $user['user_id']);

		if ($user['user_state'] == 'email_confirm')
		{
			$this->_getUserConfirmationModel()->sendEmailConfirmation($user);
		}

		return $this->_completeRegistration($user);
	}`

Do not know what this code can help in the supplement data is not?

**Comment by sgdc3** [comment] 2016-09-30 16:30
@ljacqu

**Comment by ljacqu** [comment] 2016-09-30 20:08
Thanks for the code. Let's start with the first question—how far is the Xenforo integration already?

1. If a user registers via website, can he then join the Minecraft server and use `/login` successfully?
  a. Can this user change his password on the website and still use `/login` successfully?
  b. Can this user change his password in Minecraft (`/changepassword`) and still log onto the website?

2. If a user registers in Minecraft (`/register`), is it possible for him to log onto the website?

**Comment by joestrusz** [comment] 2016-10-06 18:29
Status?

**Comment by ljacqu** [comment] 2016-10-06 18:42
Blocked by no one answering the questions in here and in the linked issue.

**Comment by joestrusz** [comment] 2016-10-06 18:53
That's unfortunate. As of right now it doesn't appear to be anywhere close.

**Comment by Eufranio** [comment] 2016-10-06 18:55
`If a user registers via website, can he then join the Minecraft server and use /login successfully?`
Yes

`Can this user change his password on the website and still use /login successfully?`
Yes

`Can this user change his password in Minecraft (/changepassword) and still log onto the website?`
No

`If a user registers in Minecraft (/register), is it possible for him to log onto the website?`
No

**Comment by joestrusz** [comment] 2016-10-06 18:57
The above is inaccurate. The answer to all these questions is NO. At least with the latest few versions of XenForo. 

The new password hash is not compatible with AuthMe. As it stores more than just the password now.

**Comment by ljacqu** [comment] 2016-10-08 08:34
@joestrusz Are you sure you configured AuthMe to use the `XENFORO` hash for passwords?

> it stores more than just the password now
Exactly, and as long as we don't know what that "more" is we're blocked. If someone is willing to have a Skype session sometime I'd be willing to give that a go so we could go through the code. Or of course if someone has enough understanding of the code to share the few sections we need to understand what is going on.

**Comment by vanthoi** [comment] 2016-10-08 19:45
Sorry. Because of this delay. The past few days I have been having some personal problems. Today I was able to continue the work. You do not care about how it is encoded just do the following. Any version can xenforo always successful login!

UPDATE xf_user_authenticate
SET data = BINARY
CONCAT(
CONCAT(
CONCAT('a:3:{s:4:"hash";s:40:"', SHA1(CONCAT(SHA1('newpass'), SHA1('salt')))),
CONCAT('";s:4:"salt";s:40:"', SHA1('salt'))
),
'";s:8:"hashFunc";s:4:"sha1";}'
),
scheme_class = 'XenForo_Authentication_Core'
WHERE user_id = 1;

//newpass:  change pass of you!
//user_id: id of user

**Comment by joestrusz** [comment] 2016-10-09 18:42
I have a XenForo site setup, the plugin installed, and ready to go. You can add me on Skype info@t0rched.com.

**Comment by sgdc3** [comment] 2016-10-09 19:00
@joestrusz Atm the latest Xenforo related code is in the master branch.

**Comment by joestrusz** [comment] 2016-10-09 19:37
@sgdc3 do you have a sample config.yml?

**Comment by vanthoi** [comment] 2016-10-12 06:32
@sgdc3 @ljacqu  How's situation for you? Looking forward to reply soon

**Comment by vanthoi** [comment] 2016-10-18 08:18
@sgdc3 @ljacqu Hello. Do not know the suggestions I made. Is there anything wrong or not? Without any answer that? Thank you!

**Comment by t0rch3d** [comment] 2016-10-18 08:35
@vanthoi The current implementation does not work. It needs to be set to use xf_user_authenticate.data [type blob] WHERE xf_user_authenticate.user_id = id field from config... as the password field when encryption type "XENFORO" is set. It appears to do the entire function within the same table currently.

**Comment by t0rch3d** [comment] 2016-10-18 08:36
Also, please merge this into the legacy branch as well if its not too difficult, time consuming etc. Many people still use 1.7.10 for most modded servers.

**Comment by DNx5** [comment] 2016-10-18 08:37
the current encryption for 'XenForo_Authentication_Core12' is ``XFBCRYPT`` not ``XENFORO``

**Comment by t0rch3d** [comment] 2016-10-18 08:37
Regardless of that, it still appears to not consider password/username are in two different DB tables.

**Comment by vanthoi** [comment] 2016-10-18 08:40
You try to use my code sent to an account password change goes. See login with success? Part ID, just get inside the user ID and then insert into the table or password. Core 12 is SHA256 encryption mechanism. But all support xenforo SHA1 encryption. I tested from 1.3.x to 1.6.9 still OK

**Comment by vanthoi** [comment] 2016-10-18 08:42
About table databases. Simply switch config xenforo max brightness will face the other table for 2 just change the classification xenforo not related to severance.

**Comment by sgdc3** [comment] 2016-10-18 11:18
>Also, please merge this into the legacy branch as well if its not too difficult, time consuming etc. Many people still use 1.7.10 for most modded servers.

The legacy jar is compiled from the same branch.

**Comment by t0rch3d** [comment] 2016-10-18 12:11
Confirmed working on 1.7.10 with legacy jar with the help of @joestrusz. There seems to be an issue when new game/site users registering via the game however. Will confirm either way.

**Comment by t0rch3d** [comment] 2016-10-19 02:17
@ljacq registration only appears to work via XenForo. If you /register in game, it creates the table data, but you get a "You must be logged in error" upon trying to use the password when logging into the website. It also appears to automatically assign role "Admin" to the user. 

However, on the flipside if you register via XenForo it seems to work just fine.

**Comment by sgdc3** [comment] 2016-10-19 08:18
@ljacqu not ljacq ;)

**Comment by t0rch3d** [comment] 2016-10-19 20:18
Confirmed again this morning. You can register in game, but it will not allow you to login to the site. Otherway is fine. 

Also assigns group Administrator apparently. Does this work with XenForo groups or is something like CommunityBridge still needed?

**Comment by t0rch3d** [comment] 2016-10-24 05:12
Bump please.

Register on Web, Login in Game = Yes
Change Password on Web, Login in Game = Yes

Register in Game with AuthMe, Login to Web = NO
Change Pass in Game with AuthMe, Login to Web = NO

*Also assigns default user as admin role only because XenForo schema doesn't have a default role assigned to the table field.

Please resolve this... a ton of people would be happy, bumping downloads and general use as a security/authentication plugin. 

Thank you!

**Comment by sgdc3** [comment] 2016-10-24 05:34
Atm @ljacqu is not available, we'll fix this with highest priority since next week.

**Comment by t0rch3d** [comment] 2016-11-12 00:59
Any update?

**Comment by t0rch3d** [comment] 2016-12-02 11:01
Bump. :dancer:

**Comment by sgdc3** [comment] 2016-12-02 13:41
@ljacqu What to do with that?

**Comment by t0rch3d** [comment] 2016-12-03 20:35
Was the "XenForo support" just a marketing ploy? I will have to switch to something else. I was told this was going to be finished months ago. It works... 50%. Users whom register in game cannot login to XenForo. May have something to do with the "remember_key". Please advise.

**Comment by ljacqu** [comment] 2016-12-03 20:50
Sorry @t0rch3d, I haven't had this on my radar at all. It didn't help that I had to go to the military recently (as I live in one of the only European countries that still has mandatory conscription...). 

If you have the possibility to have a skype session with me I'm certain we can dig through the code and get it working. I don't have access to the xenforo sources so as long as that isn't possible there will probably not be much progress. 

I'm aware of the info in https://github.com/Xephi/AuthMeReloaded/issues/957#issuecomment-252444407, and thank you for that, but again, not even knowing how that database looks, it won't be possible for me to reliably implement something in Java based on that SQL snippet.

**Comment by t0rch3d** [comment] 2016-12-03 20:58
I can provide you with PHPMyAdmin access and a Skype session. What time zone are you in? You can add me on Skype here: info@worldautomation.net. Our pack is available on Technic, but the O'Reilly Console Client connects find to it for testing purposes with AuthMe. Shoot me a contact request, and we can find a time to sit down and hash this out. I have extensive PHP/MySQL knowledge but little to no Java experience.

**Comment by ljacqu** [comment] 2016-12-03 21:22
This is great news! I'm in GMT+1 (i.e. it's 10:22 PM for me right now). I've sent an email to the address on your Github profile, hopefully this can get the ball rolling :)

**Comment by t0rch3d** [comment] 2016-12-04 03:51
Ok, so technically the support is there. On my server I used XFBCRYPT type, supplied all the necessary database table fields etc. However, the symptom of the "lack of support" comes from users registering in game, and their forum account being created, but simply inaccessible as the necessary "other" user related tables aren't being adjusted/created. Here's a hack:

First, set a default of your default group ID, in my case "2", in the xf_user table for fields user_group_id and permission_combination_id in that table. So all new insert queries that don't specify a group ID will be supplied your default user group automatically. Otherwise, the users wont be able to login still. 

Now, here's the semi tricky part. Add a trigger on the xf_user table to insert a new row into xf_user_privacy. Here's the code you can paste into phpMyAdmin:

`delimiter $$
begin
  insert into xf_user_privacy (user_id, allow_view_profile, allow_post_profile, allow_send_personal_conversation, allow_view_identities, allow_receive_news_feed)
 values (NEW.user_id, "everyone", "members", "members", "everyone", "everyone"); 
end;
delimiter;`

With these adjustments to your DB, you will now have fully functional 2-way registration, password change and login. 

I am currently using both CommunityBridge and AuthMe simultaneously. AuthMe is a great plugin and now that this hurdle has been semi fixed I can move on to tailoring it more for my server. 

Thank you for your hard work on the plugin everyone. Love it.

**Comment by ljacqu** [comment] 2016-12-09 06:22
I haven't forgotten about this! I'll try to hit you up on Skype this weekend

**Comment by sgdc3** [comment] 2017-05-04 14:10
@ljacqu Should we move this to 5.4?

**Comment by ljacqu** [comment] 2017-05-04 15:31
If you realistically think you will do it – sure! I didn't move it over because it seems blocked until someone who knows Xenforo comes along

**Comment by sgdc3** [comment] 2017-07-06 16:25
The main feature should be working, registration via forum is not required

**Comment by t0rched** [comment] 2017-07-10 02:47
@sgdc3 will verify shortly. Setting my server backup on AuthMe/cracked. Will reply with any issues.

**Comment by sgdc3** [comment] 2017-07-10 14:54
No, download this file: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.3.3-SNAPSHOT.jar it supports any version since 1.7.10

**Comment by sgdc3** [comment] 2017-10-17 07:05
@t0rched Did it work? ;)

**Comment by t0rched** [comment] 2017-11-17 21:37
Testing. Once I find the new download. Ugh.

**Comment by sgdc3** [comment] 2017-11-17 21:37
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by t0rched** [comment] 2017-11-17 21:38
Thank you. Testing with XenForo 1.5.x and http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.4-SNAPSHOT.jar

**Comment by t0rched** [comment] 2017-11-17 21:58
Server won't even start with 5.4 latest build. I thought I had to use an older build to achieve function on 1.7.10? Cause' this one certainly doesn't work.

**Comment by t0rched** [comment] 2017-11-17 22:23
I guess I am confused. Do I use the xf_user table at the top of the AuthMe config, or the xf_user_authenticate table? Either way, there are a whole lot of table options there for fields that don't exist. I don't mind the Minecraft server fields IE location, x,y,x etc.. But there is no "realName" field in either of the two main user tables of XF...

**Comment by t0rched** [comment] 2017-11-18 02:40
Verified working 100% both directions with Thermos-1614, AuthMe-5.4-SNAPSHOT (latest as of this post). This, CommunityBridge for Spigot, and XenForo appear to be my servers holy trinity for full account/sql player immersion with a community.

Thank you developers, contributors and all involved. Verified 100% working. 

PM me for config help.

**Comment by ljacqu** [comment] 2017-11-18 08:13
hi @t0rched , this is excellent (and surprising) news! Thanks for testing and for your feedback.

Do you think you could help us with having a section on Xenforo at https://github.com/AuthMe/AuthMeReloaded/wiki/Forum-integrations akin to the phpBB one?

**Comment by t0rched** [comment] 2017-11-18 18:30
Yes, I will have some time. I can package up my config and write some notes. Thank you for the wonderful piece of software :D

**Comment by ljacqu** [comment] 2017-11-18 20:21
@t0rched, excellent, thank you :)

**Comment by t0rched** [comment] 2017-11-19 05:59
Testing mostly complete. All things appear to be working 100%. Will test the additional features such as email resets and all that jazz, then post in completion the entirety of the setup. Cheers.

**Comment by t0rched** [comment] 2017-12-03 02:30
So, there are issues. It *mostly* works. It doesn't seem to assign the permission roles for the chosen user group after registering. I am debugging this now as before. Possible fix with triggers. Will advise.

**Comment by t0rched** [comment] 2017-12-03 02:52
This is the issue...

ALTER TABLE xf_user MODIFY COLUMN permission_combination_id INT(10) NOT NULL DEFAULT '2';

Was one of my above suggestions for a hack. This actually changes based on installation. Best to let the user set the default field value here, and all works as it should 100%... However authme appears to be setting this value... just remove it.

**Comment by t0rched** [comment] 2017-12-03 22:16
I have a forked version that is working temporarily for XF. I will try and build a patch and add the needed config line.

**Comment by sgdc3** [comment] 2017-12-03 23:00
@t0rched That would be amazing, thank you :D

**Comment by ljacqu** [comment] 2018-01-21 18:15
Hi @KipperedSnack, any news on the xenforo front?

**Comment by ljacqu** [comment] 2018-02-02 19:14
Closing this as it has the milestone 5.4.0 on it (and we did do some work within 5.4.0). Please open a follow-up issue.

**Closed by ljacqu** 2018-02-02 19:14 UTC
Labels: Status: no answer, Type: bug
