### ISSUE TITLE
In the last build (#2138) disrupted work the "sessions"

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1650] opened 2018-10-06 00:35 UTC
In the last build (#2138) disrupted work the "sessions"
The function no longer works:

```
settings:
    sessions:
        # Do you want to enable the session feature?
        # If enabled, when a player authenticates successfully,
        # his IP and his nickname is saved.
        # The next time the player joins the server, if his IP
        # is the same as last time and the timeout hasn't
        # expired, he will not need to authenticate.
        enabled: true
        # After how many minutes should a session expire?
        # A player's session ends after the timeout or if his IP has changed
        timeout: 10
```
Minecraft Versions: 1.12.2

**Comment by sgdc3** [comment] 2018-10-08 18:26
@Y3cy it is configurable

**Comment by Roper89** [comment] 2018-10-09 11:06
I have one server, I do not have bungee. Only AuthMeReloaded build (#2138)
On the old version 5.4.0, everything works for me.

I tested with the default settings, only included the session:

```
settings:
    sessions:
         enabled: true
         timeout: 10
```

**Comment by sgdc3** [comment] 2018-10-09 13:36
\#2137 works as intended?

**Comment by sgdc3** [comment] 2018-10-09 13:37
we need to find out which change caused this issue

**Comment by Roper89** [comment] 2018-10-10 07:54
It's hard for me to tell which assembly this problem started with.
I noticed that there is no file creation "GeoIP.dat"
If you use the old version (Example build#1993), then the file is created and then there are no problems with the latest build.

**Comment by sgdc3** [comment] 2018-10-10 10:41
wtf this is super strange O_o

**Comment by sgdc3** [comment] 2018-10-10 10:42
@DNx5 @games647 @Hex3l any idea guys?

**Comment by r4nx** [comment] 2018-10-28 10:10
The same thing: AuthMe 5.5.0-SNAPSHOT build n.2149, Spigot 1.13.2, sessions don't work at all.

**Comment by 7wOv6ySCjo** [comment] 2018-11-02 16:22
This is a critical bug.
Enter with nick: md_5 and sessions work fine.
Enter with nick: Xephi and sessions don't work. 
md_5 it has lowercase only.
Xephi has a capital letter.
Session only seems to work well with nicks that are written in lowercase.
AuthMe saves the nicknames in lowercase only, that is why the session never corresponds.

**Comment by krusic22** [comment] 2018-11-18 12:44
Can someone try build 2135?

**Comment by sgdc3** [comment] 2018-11-29 23:41
@Roper89 can you post your full config please?

**Comment by Roper89** [comment] 2018-11-29 23:46
@sgdc3 https://pastebin.com/pGPqZfmh

**Comment by sgdc3** [comment] 2018-11-29 23:47
this is a sqlite only issue as far as we know, can you tey running mysql in the meantime?

**Comment by sgdc3** [comment] 2018-11-29 23:48
so we can be sure it is a sqlite only problem and look into possible causes @Roper89

**Comment by Roper89** [comment] 2018-11-29 23:58
@sgdc3  My hosting does not give access to the database.

**Comment by ljacqu** [comment] 2018-12-04 17:58
There's a problem with the UPDATE statements generated by the sql columns library. It uses the player's name in its correct casing while it should be using the name in all lowercase.

**Comment by ljacqu** [comment] 2018-12-04 18:06
Hi @Roper89 @7wOv6ySCjo , this should be fixed as of build nr. 2182. https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
Could you kindly confirm that this is fixed on your side as well such that we can close this bug? Thanks

**Comment by Roper89** [comment] 2018-12-04 20:41
@ljacqu Thanks It works.

**Comment by ljacqu** [comment] 2018-12-04 20:59
Thanks for the feedback, @Roper89 :)

**Closed by ljacqu** 2018-12-04 20:59 UTC
Labels: Priority: critical, Status: please verify, Type: bug
