### ISSUE TITLE
java.sql.SQLException: Unknown system variable 'tx_isolation'

### ISSUE THREAD

**Issue by SaaYy** [AuthMe/AuthMeReloaded#1862] opened 2019-07-11 13:17 UTC
### What behaviour is observed:
Can't connect to database

### What behaviour is expected:
Successful connection to database

### Steps/models to reproduce:
Server startup

### Plugin list:
ArmorEquipEvent v1.6.4
AuthMe v5.4.0-b1877
Autorank v4.2.6
BountyHunters v2.2.1
ChatItem v1.3.6.4
ChatManager v3.4.11
CommandTimer v2.4.2
CoreProtect v2.12.0
CrateReloaded v2.0.12
CrazyAuctions v1.2.9
CrazyEnchantments v1.7.9.4
CreativeNbtControl v1.12
CustomTab v1.1
EnjinMinecraftPlugin v3.4.3
Essentials v2.17.0.0
EssentialsSpawn v2.17.0.0
FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432
GriefPrevention v13.9.1
GroupManager v0.2.0
Hawk vBETA 1906.1
HolographicDisplays v2.3.2
ImageOnMap v3.1
ItemNBTAPI v1.8.3-SNAPSHOT
LabyModAPI v1.1
LongMessages vv1.1
MCJukebox v2.6.2
MobFarmManager v1.5.1.3
MySQL v1.0.2
NBTEditor v1.2
Parties v2.5.2
PlaceholderAPI v2.10.3
PlayerReport v3.1.0
PluginConstructorAPI v1.0.51
PluginLibrary v1.2.1
PlugMan v2.0.8
Profiles v2.1
ProtocolLib v4.4.0
RandomTP v1.0.7.0
RedstoneClockPreventer v1.3.1
ServerListPlus v3.4.8
ServerSigns v4.5.1
ShopChest v1.6.0.1
Shopkeepers v1.68
SilkSpawners v5.0.2
SkinsRestorer v13.6.2
SQLiteLib v1.3
StackMob v2.2.18
Statz v1.0
SuperbVote v0.5.2-1.12
TradeSystem v1.1.1
Vault v1.7.2-b107
ViaRewind v1.4.0
ViaVersion v2.1.2
Votifier v3.0.0-SNAPSHOT
VPNGuard v3.1
WDLCompanion v1.2.0
WDLCompanionGriefPreventionSupport v1.0.0
WDLCompanionWorldGuardSupport v0.0.1
WorldBorder v1.8.6
WorldEdit v6.1.3;7a097ca
WorldGuard v6.1

### Environment description
MySQL

### AuthMe build number:
v5.4.0-b1877 (already tried to change to the latest beta build, and still no work)

### Error Log:
https://pastebin.com/wL0y15Pf

### Configuration:
https://pastebin.com/dKPbsRNt

**Comment by games647** [comment] 2019-07-11 13:20
Duplicate of #1779

**Closed by games647** 2019-07-11 13:20 UTC
