### ISSUE TITLE
SQL error on startup

### ISSUE THREAD

**Issue by KupKa1221** [AuthMe/AuthMeReloaded#2374] opened 2021-06-30 13:43 UTC
### What behaviour is observed:
What happened?
SQL issue

### What behaviour is expected:
What did you expect?
Server startup
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungee with MySQL
### AuthMe build number:
This can be found by running `/authme version`
2480
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
https://pastebin.com/MX8kcW8c
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/QKafuKZr

**Comment by sgdc3** [comment] 2021-07-01 12:03
Try to set "mySQLUseSSL" to false

**Comment by KupKa1221** [comment] 2021-07-08 08:35
Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by sgdc3** [comment] 2021-08-21 20:26
Duplicate of #1779

**Closed by sgdc3** 2021-08-21 20:26 UTC
Labels: Type: bug
