### ISSUE TITLE
AUTHME message

### ISSUE THREAD

**Issue by AirCraze** [AuthMe/AuthMeReloaded#2348] opened 2021-06-06 22:16 UTC
### What behaviour is observed:
What happened?
AuthMe blocks join messages from coming in from EssentialsX
### What behaviour is expected:
What did you expect?
I except authme to use EssentialsX custom join messages
### Steps/models to reproduce:
The actions that cause the issue
The whole plugin itself
### Plugin list:
This can be found by running `/pl`
Just EssentialsX, AuthMe
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
TacoSpigot (Which is basically PaperSpigot)
### AuthMe build number:
This can be found by running `/authme version`
5.6.0-beta2
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
None
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
       forceLoginAfterRegister: false
    # Enable to display the welcome message (welcome.txt) after a login
    # You can use colors in this welcome.txt + some replaced strings:
    # {PLAYER}: player name, {ONLINE}: display number of online players,
    # {MAXPLAYERS}: display server slots, {IP}: player ip, {LOGINS}: number of players logged,
    # {WORLD}: player current world, {SERVER}: server name
    # {VERSION}: get current bukkit version, {COUNTRY}: player country
    useWelcomeMessage: false
    # Broadcast the welcome message to the server or only to the player?
    # set true for server or false for player
    broadcastWelcomeMessage: false
    # Should we delay the join message and display it once the player has logged in?
    delayJoinMessage: false
    # The custom join message that will be sent after a successful login,
    # keep empty to use the original one.
    # Available variables:
    # {PLAYERNAME}: the player name (no colors)
    # {DISPLAYNAME}: the player display name (with colors)
    # {DISPLAYNAMENOCOLOR}: the player display name (without colors)
    customJoinMessage: ''
    # Should we remove the leave messages of unlogged users?
    removeUnloggedLeaveMessage: false
    # Should we remove join messages altogether?
    removeJoinMessage: false
    # Should we remove leave messages altogether?
    removeLeaveMessage: false
    # Do we need to add potion effect Blinding before login/register?
    applyBlindEffect: false
    # Do we need to prevent people to login with another case?
    # If Xephi is registered, then Xephi can login, but not XEPHI/xephi/XePhI
    preventOtherCase: true

**Comment by sgdc3** [comment] 2021-06-07 11:04
@AirCraze told me his issue was caused by the ChatControl plugin, closing

**Closed by sgdc3** 2021-06-07 11:04 UTC
Labels: Type: bug
