### ISSUE TITLE
AuthMe v5.6.0-SNAPSHOT-b2345

### ISSUE THREAD

**Issue by successed** [AuthMe/AuthMeReloaded#1962] opened 2019-12-16 02:38 UTC
Authme not workt:

[AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2345

Console log:
![Screenshot_32](https://user-images.githubusercontent.com/13768414/70875215-37e59580-1fc6-11ea-9218-9427a9682589.png)

Server version : PAPER 1.14.4 #237

**Comment by ljacqu** [comment] 2019-12-16 08:47
Duplicate of #1945. It should work with the latest dev build

**Closed by ljacqu** 2019-12-16 08:47 UTC
Labels: Type: bug
