### ISSUE TITLE
captcha after login/register

### ISSUE THREAD

**Issue by culjketa** [AuthMe/AuthMeReloaded#1893] opened 2019-08-17 22:28 UTC
Hey any free devs that can implement captcha after login to be a requirement so after they login or register they have to enter captcha to play. Need it because of some advanced spam bots that are joining thru compass hub to my factions and spamming hard, please.

**Comment by ljacqu** [comment] 2019-08-23 17:22
Closing as duplicate of #1817, but it's interesting to hear someone else is interested in this

**Closed by ljacqu** 2019-08-23 17:22 UTC
