### ISSUE TITLE
A lot of login messages

### ISSUE THREAD

**Issue by Eufranio** [AuthMe/AuthMeReloaded#1532] opened 2018-03-16 16:38 UTC
There's a lot of messages that are sent on login regardless the login state of the player, see: https://prnt.sc/is3ebi

**Comment by Eufranio** [comment] 2018-03-17 02:13
Yes.

**Comment by ljacqu** [comment] 2019-06-22 19:15
Closing as duplicate of #1747 (intentionally closing this older one so maybe the issue that is on the first page will stay in our mind better)

**Closed by ljacqu** 2019-06-22 19:15 UTC
Labels: Topic: bungeecord, Type: question
